language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - 7.0

before_script:
  - cd ./tests/
  - wget https://phar.phpunit.de/phpunit.phar --no-check-certificate

script:
  php phpunit.phar ./ --coverage-text
